"""add document id to usage logs

Revision ID: bf9905658613
Revises: 56cc47c87e0f
Create Date: 2026-09-26 21:08:16.470850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf9905658613'
down_revision: Union[str, Sequence[str], None] = '56cc47c87e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('document_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_usage_logs_document_id'), 'usage_logs', ['document_id'], unique=False)
    op.create_foreign_key(None, 'usage_logs', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_index(op.f('ix_usage_logs_document_id'), table_name='usage_logs')
    op.drop_column('usage_logs', 'document_id')
    # ### end Alembic commands ###
