"""add soft delete to documents

Revision ID: d9654b3d071a
Revises: aeddec3dc079
Create Date: 2026-09-26 14:17:38.101597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9654b3d071a'
down_revision: Union[str, Sequence[str], None] = 'aeddec3dc079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('deleted_by', sa.String(), nullable=True))
    # op.create_foreign_key(None, 'documents', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(
        'fk_documents_deleted_by_users',
        'documents',
        'users',
        ['deleted_by'],
        ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    # op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(
        'fk_documents_deleted_by_users',
        'documents',
        type_='foreignkey'
    )
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'deleted_at')
    # ### end Alembic commands ###
